### ISSUE TITLE
Build fails due to error related to localization

### ISSUE THREAD

**Issue by ghost** [kaandedeoglu/Shark#17]
I am running shark using the following command
```sh
if [ -x "$(command -v shark)" ]; then
    shark "$PROJECT_FILE_PATH" "$PROJECT_DIR/$PROJECT_NAME"
else
    echo "error: shark not installed, run command brew install kaandedeoglu/formulae/shark"
fi
```

It fails with following error
> Fatal error: Error raised at top level: Shark.LocalizationBuilderError.invalidLocalizableStringsFile(path: "/Users/username/app-name/app-name/app-name/Base.lproj/LaunchScreen.storyboard/en.lproj/LaunchScreen.strings"): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1001.8.63.13/swift/stdlib/public/core/ErrorType.swift, line 200

Localization is enabled for the `LaunchScreen.storyboard`.

The `LaunchScreen.storyboard` is found at file path `/Users/username/app-name/app-name/app-name/Base.lproj/LaunchScreen.storyboard`.

The `LaunchScreen.strings` file for English is found at file path `/Users/username/app-name/app-name/app-name/en.lproj/LaunchScreen.strings` and not at the file path mentioned in the error (`/Users/username/app-name/app-name/app-name/Base.lproj/LaunchScreen.storyboard/en.lproj/LaunchScreen.strings`)

**Comment by kaandedeoglu** [comment]
Hey, thanks for reporting, I've just pushed version 1.1.4 here and on homebrew. Please see if this fixes this issue. 

Just to give a little more context, I ended up ignoring the `.strings` files for the storyboards. Two reasons for this:
- Since the identifiers are automagically generated by Xcode, I don't think it makes sense for Shark to consume these
- I've had problems with the XcodeProj project I'm using to get file paths of the resources. It seems to give me faulty paths (as you've observed) for such `.strings` files. I suppose this is happening since Xcode is displaying them as if they live under the storyboard file, where in reality they live elsewhere.

**Comment by ghost** [comment]
Yes, 1.1.4 fixes the issue.

Thank you.
