### ISSUE TITLE
Automatic preview updating paused

### ISSUE THREAD

**Issue by denizdogan** [kaandedeoglu/Shark#42]
Unless you run the Shark script with "For install builds only", the automatic preview of SwiftUI in Xcode keeps popping up "Automatic preview updating paused". I'm guessing this is because it detects changes to the relevant source code.

**Comment by mickeyl** [comment]
Indeed. Shark breaks SwiftUI previews unless you've checked the "For install builds only" checkbox.

This relates to #25.

Off the top of my head, there are two approaches:

1.) Let Xcode handle this by adding the necessary dependencies (Storyboard files, Asset catalogues, and Localizable.strings) to the Input files and adding the output file – perhaps even add a command line Switch where Shark emits this list.

2.) Let Shark handle this by saving the timestamps and/or hashes of its (computed) input files and not generating any new output if nothing has changed.

My gut feeling is that 2.) might be the better way. What do you think?

**Comment by denizdogan** [comment]
@mickeyl I would agree that 2) seems like a more suitable solution! I would probably go for hashes myself, unless that proves too computationally expensive.

**Comment by mickeyl** [comment]
@denizdogan [This](https://github.com/kaandedeoglu/Shark/commit/a45505f6b83ebc57e4bd007e1773febc143d4f7e) is the most simple solution I could come up with. Instead of caching anything or computing hashes, let's just compare the existing output with the new output. Since we're typically not dealing with megabyte-long files, I assume this to be a workable solution.

Please confirm whether this fixes it for you.

**Comment by denizdogan** [comment]
@mickeyl The issue seems to have been resolved! Thank you!

**Comment by denizdogan** [comment]
@mickeyl I got a small example working here: https://github.com/denizdogan/NavigationLink-Bug

The bug is that I expect to land on ViewD, but it stops at ViewC -> ViewD -> ViewC
