### ISSUE TITLE
Enforcement `CaseIterable` needs to be optional

### ISSUE THREAD

**Issue by 404wasfound** [kaandedeoglu/Shark#48]
By making all the enums `CaseIterable` you essentially breaking all the projects which have their resources separated in different folders, cause now all the resources of the same type are under one huge enum, instead of the nested ones. Have to fork the tool to fix it now.

**Comment by mickeyl** [comment]
I'm not sure I understand that. The nesting is independent from the attribute `CaseIterable`. Can you show me a diff for you between an older version and a newer one, so I can see how it breaks?

**Comment by 404wasfound** [comment]
hey there @mickeyl! thanx for the response! tbh do not even know how to show the entire thing, will share a screenshot with some parts of the diff so you have a better idea

So we used to have all the resources separated in folders, on that screenshot you see the deleted parts of previously generated enum for images
<img width="963" alt="Screenshot 2022-11-07 at 16 50 56" src="https://user-images.githubusercontent.com/16050010/200354186-469c1388-f0f4-4a16-8eeb-b3204f222025.png">


And now all the resources are just under one resource specific enum (`I`, `C` etc.)
<img width="882" alt="Screenshot 2022-11-07 at 16 52 55" src="https://user-images.githubusercontent.com/16050010/200354694-d7b5081f-adfa-4371-b2a5-6cb15186aca2.png">

**Comment by 404wasfound** [comment]
So if we take for example the very first case from the screenshot with deleted parts, `ic_standard_business`, in the code we referenced it as `I.Address.ic_standard_business`, but now it is just `I.standard_business`. Naturally that happened to all the resources.

Imho previous approach was better especially for the projects with tons of different resources, was way easier to navigate and find resources case enums reflected the folder structure in resources.

**Comment by mickeyl** [comment]
@404wasfound Ah, I think this is due to the new *corrected* folder handling. Please have a look at the [README](https://github.com/kaandedeoglu/Shark) again. If you want Shark to turn a folder into a namespace, you need to check the _[x] Provides Namespace_ below

![](https://user-images.githubusercontent.com/167469/190901709-d4cf52f9-43bb-4c5e-bc4e-dfce24dd2638.png)

for every folder you're using. Previously, Shark did create a namespace for every folder, no matter whether the checkbox was ticked or not. The new behavior is correct, although it requires you to adjust your projects. Sorry for the inconvenience.

Please check after checking the folder checkboxes whether this returns your Shark file to the previous state.

**Comment by 404wasfound** [comment]
```
provided you have configured the respective Xcode setting Provides Namespace
```

ooohhhh now I see ... so the previous folders handling was not correct? will try it now, thank you for the info and sorry for bothering!

**Comment by 404wasfound** [comment]
@mickeyl worked, thank you very much!
